services:
  - type: web
    name: macgly
    runtime: node
    buildCommand: cd apps/web && npm install && npm run build && cd ../api && npm install
    startCommand: node apps/api/src/server.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: MAILERSEND_API_KEY
        sync: false
