/**
 * Migration: Change KYC document delivery type from 'upload' to 'authenticated'.
 *
 * WHY:
 *   KYC documents uploaded via POST /vendors/kyc/documents use the default
 *   Cloudinary delivery type ('upload'), which means the stored URL is publicly
 *   accessible to anyone who knows or guesses it.  The signed URL generated by
 *   CloudinaryAdapter.signedUrl() only enforces access control when the resource
 *   has delivery type 'authenticated'.  Until this migration runs, the signed URL
 *   is cosmetic — the plain URL still works without authentication.
 *
 * WHAT IT DOES:
 *   1. Finds all users with kycDocuments in the database.
 *   2. For each document, calls the Cloudinary Admin API to change delivery type.
 *   3. Records the updated URL in MongoDB so existing references remain valid.
 *   4. Writes a progress log to MIGRATION_LOG_PATH (never prints URLs to stdout).
 *
 * SAFETY GUARANTEES:
 *   - Dry-run mode (default): prints counts only, makes no changes.
 *   - Idempotent: skips documents already in 'authenticated' delivery type.
 *   - Resumable: reads the progress log on restart and skips completed IDs.
 *   - Never prints document URLs to stdout/stderr.
 *   - Roll-back: running with --rollback changes type back to 'upload'.
 *
 * USAGE:
 *   # Dry run (always safe — no changes made)
 *   node src/scripts/migrateKycToAuthenticated.js --dry-run
 *
 *   # Actual migration (run in production AFTER verifying dry-run output)
 *   node src/scripts/migrateKycToAuthenticated.js
 *
 *   # Roll back if something goes wrong
 *   node src/scripts/migrateKycToAuthenticated.js --rollback
 *
 * PREREQUISITES:
 *   - MONGO_URI, CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY, CLOUDINARY_API_SECRET
 *     must be set in the environment (.env or process.env).
 *   - The script must be run from the apps/api directory:
 *       cd apps/api && node src/scripts/migrateKycToAuthenticated.js --dry-run
 */

require('dotenv').config({ path: require('path').resolve(__dirname, '../../../../.env') });

const mongoose = require('mongoose');
const cloudinary = require('cloudinary');
const fs = require('fs');
const path = require('path');

const MONGO_URI = process.env.MONGO_URI;
const CLOUD_NAME = process.env.CLOUDINARY_CLOUD_NAME;
const API_KEY = process.env.CLOUDINARY_API_KEY;
const API_SECRET = process.env.CLOUDINARY_API_SECRET;

const DRY_RUN = process.argv.includes('--dry-run');
const ROLLBACK = process.argv.includes('--rollback');
const TARGET_TYPE = ROLLBACK ? 'upload' : 'authenticated';
const SOURCE_TYPE = ROLLBACK ? 'authenticated' : 'upload';

const MIGRATION_LOG_PATH = path.join(__dirname, '..', '..', '.kyc-migration-progress.json');
const BATCH_SIZE = 10; // Cloudinary rate limits: stay conservative

if (!MONGO_URI || !CLOUD_NAME || !API_KEY || !API_SECRET) {
  console.error('FATAL: Missing required environment variables. Check .env file.');
  console.error('Required: MONGO_URI, CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY, CLOUDINARY_API_SECRET');
  process.exit(1);
}

cloudinary.config({ cloud_name: CLOUD_NAME, api_key: API_KEY, api_secret: API_SECRET });

// Extract components from a stored Cloudinary URL
function extractUrlParts(url) {
  if (!url || typeof url !== 'string') return null;
  try {
    const match = url.match(/\/(image|video|raw)\/(upload|authenticated)\/(?:v\d+\/)?(.+?)(?:\.([a-z0-9]+))?$/i);
    if (!match) return null;
    return {
      resourceType: match[1],           // 'image', 'video', or 'raw'
      publicId: match[3],               // path without version or extension
      extension: match[4] || null,      // file extension, e.g. 'pdf', 'jpg'
    };
  } catch { return null; }
}

// Build the URL for a given delivery type (does NOT expose the URL value in logs)
function buildUrl(publicId, deliveryType, resourceType, extension, version) {
  const versionSegment = version ? `v${version}/` : '';
  const ext = extension ? `.${extension}` : '';
  return `https://res.cloudinary.com/${CLOUD_NAME}/${resourceType}/${deliveryType}/${versionSegment}${publicId}${ext}`;
}

// Load progress log from a previous (interrupted) run
function loadProgress() {
  try {
    if (fs.existsSync(MIGRATION_LOG_PATH)) {
      return JSON.parse(fs.readFileSync(MIGRATION_LOG_PATH, 'utf8'));
    }
  } catch { /* ignore */ }
  return { completedDocIds: [], failedDocIds: [], runAt: null };
}

// Persist progress so the migration is resumable
function saveProgress(progress) {
  fs.writeFileSync(MIGRATION_LOG_PATH, JSON.stringify({ ...progress, updatedAt: new Date().toISOString() }, null, 2));
}

async function migrate() {
  const mode = DRY_RUN ? 'DRY-RUN' : (ROLLBACK ? 'ROLLBACK' : 'MIGRATE');
  console.log(`\n=== KYC Cloudinary Migration [${mode}] ===`);
  if (DRY_RUN) {
    console.log('No changes will be made. Pass --dry-run to run without changes.');
  }

  await mongoose.connect(MONGO_URI);
  console.log('Connected to MongoDB.\n');

  // Load the raw User collection — avoid loading the full Mongoose model to keep
  // this script self-contained and avoid circular dependency issues.
  const db = mongoose.connection.db;
  const users = db.collection('users');

  // Find all vendors with at least one kycDocument
  const vendorCursor = users.find(
    { role: 'vendor', 'vendorProfile.kycDocuments.0': { $exists: true } },
    { projection: { _id: 1, 'vendorProfile.kycDocuments': 1 } },
  );

  const progress = loadProgress();
  const completedSet = new Set(progress.completedDocIds || []);
  const failedSet = new Set(progress.failedDocIds || []);

  let totalVendors = 0;
  let totalDocs = 0;
  let uploadTypeDocs = 0;
  let authenticatedTypeDocs = 0;
  let skippedDocs = 0;
  let migratedDocs = 0;
  let failedDocs = 0;

  const operations = []; // Bulk MongoDB update operations

  for await (const vendor of vendorCursor) {
    totalVendors++;
    const docs = vendor.vendorProfile?.kycDocuments || [];

    for (const doc of docs) {
      totalDocs++;
      const docId = doc._id?.toString();
      const url = doc.url || '';

      const isUploadType = url.includes('/image/upload/') || url.includes('/raw/upload/') || url.includes('/video/upload/');
      const isAuthType = url.includes('/image/authenticated/') || url.includes('/raw/authenticated/') || url.includes('/video/authenticated/');

      if (isUploadType) uploadTypeDocs++;
      if (isAuthType) authenticatedTypeDocs++;

      // Already in target state
      const alreadyDone = ROLLBACK ? isUploadType : isAuthType;
      if (alreadyDone || completedSet.has(docId)) {
        skippedDocs++;
        continue;
      }

      // Only migrate documents that are currently in source type
      const needsMigration = ROLLBACK ? isAuthType : isUploadType;
      if (!needsMigration) {
        skippedDocs++;
        continue;
      }

      const parts = extractUrlParts(url);
      if (!parts) {
        console.warn(`[WARN] Could not parse URL for document ${docId} — skipping`);
        failedDocs++;
        failedSet.add(docId);
        continue;
      }

      const { publicId, resourceType, extension } = parts;

      if (DRY_RUN) {
        // Just count — do NOT print the URL or publicId
        migratedDocs++;
        continue;
      }

      // Migrate in Cloudinary
      try {
        const result = await cloudinary.api.update(publicId, {
          type: SOURCE_TYPE,
          to_type: TARGET_TYPE,
          resource_type: resourceType,
        });

        // The public_id is unchanged; only the delivery type prefix in the URL changes.
        const newUrl = buildUrl(publicId, TARGET_TYPE, resourceType, extension, result.version);

        // Queue a MongoDB update to change the stored URL for this specific document
        operations.push({
          updateOne: {
            filter: { _id: vendor._id, 'vendorProfile.kycDocuments._id': doc._id },
            update: { $set: { 'vendorProfile.kycDocuments.$.url': newUrl } },
          },
        });

        migratedDocs++;
        completedSet.add(docId);
      } catch (err) {
        console.error(`[ERROR] Failed to migrate document ${docId}: ${err.error?.message || err.message}`);
        failedDocs++;
        failedSet.add(docId);
      }

      // Flush Mongo operations in batches
      if (operations.length >= BATCH_SIZE) {
        await users.bulkWrite(operations.splice(0));
        saveProgress({ completedDocIds: [...completedSet], failedDocIds: [...failedSet] });
        console.log(`  Progress: ${migratedDocs} migrated, ${failedDocs} failed, ${skippedDocs} skipped...`);
        // Brief pause to respect Cloudinary API rate limits (~250 req/hr for Admin API)
        await new Promise((r) => setTimeout(r, 500));
      }
    }
  }

  // Flush remaining operations
  if (!DRY_RUN && operations.length > 0) {
    await users.bulkWrite(operations);
    saveProgress({ completedDocIds: [...completedSet], failedDocIds: [...failedSet] });
  }

  await mongoose.disconnect();

  console.log('\n=== Migration Summary ===');
  console.log(`Mode:                ${mode}`);
  console.log(`Total vendors:       ${totalVendors}`);
  console.log(`Total documents:     ${totalDocs}`);
  console.log(`  upload type:       ${uploadTypeDocs}`);
  console.log(`  authenticated type:${authenticatedTypeDocs}`);
  console.log(`Skipped (already ok):${skippedDocs}`);
  console.log(`Migrated:            ${migratedDocs}`);
  console.log(`Failed:              ${failedDocs}`);

  if (!DRY_RUN && failedDocs > 0) {
    console.log(`\nFailed document IDs logged to: ${MIGRATION_LOG_PATH}`);
    console.log('Re-run the script to retry failed documents.');
  }

  if (DRY_RUN) {
    console.log(`\nDRY-RUN complete. ${uploadTypeDocs} document(s) would be migrated to 'authenticated' type.`);
    console.log('To execute, re-run without --dry-run.');
  }

  if (failedDocs > 0) process.exit(1);
}

migrate().catch((err) => {
  console.error('Migration failed with unexpected error:', err.message);
  process.exit(1);
});
