require('dotenv').config({ path: require('path').resolve(__dirname, '../../.env') });
const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');

const MONGO_URI = process.env.MONGO_URI || 'mongodb://localhost:27017/shop';

mongoose.connect(MONGO_URI).then(async () => {
  const db = mongoose.connection.db;
  const now = new Date();

  // Replace categories
  await db.collection('categories').deleteMany({});
  const cats = await db.collection('categories').insertMany([
    { name: 'Power Tools', slug: 'power-tools', description: 'Electric and battery-powered tools', displayOrder: 1, isActive: true, createdAt: now, updatedAt: now },
    { name: 'Hand Tools', slug: 'hand-tools', description: 'Manual tools for professionals', displayOrder: 2, isActive: true, createdAt: now, updatedAt: now },
    { name: 'Spare Parts', slug: 'spare-parts', description: 'Genuine spare parts and components', displayOrder: 3, isActive: true, createdAt: now, updatedAt: now },
    { name: 'Machines', slug: 'machines', description: 'Industrial machines and equipment', displayOrder: 4, isActive: true, createdAt: now, updatedAt: now },
    { name: 'Safety Equipment', slug: 'safety', description: 'PPE and safety gear', displayOrder: 5, isActive: true, createdAt: now, updatedAt: now },
    { name: 'Measuring Tools', slug: 'measuring-tools', description: 'Precision measurement instruments', displayOrder: 6, isActive: true, createdAt: now, updatedAt: now },
    { name: 'Welding', slug: 'welding', description: 'Welding machines and accessories', displayOrder: 7, isActive: true, createdAt: now, updatedAt: now },
    { name: 'Cutting Tools', slug: 'cutting-tools', description: 'Blades, discs and cutting accessories', displayOrder: 8, isActive: true, createdAt: now, updatedAt: now },
  ]);
  const c = cats.insertedIds;
  console.log('Categories:', Object.keys(c).length);

  // Clear old products
  await db.collection('products').deleteMany({});

  const products = [
    { title: 'Bosch GSB 550 Impact Drill', slug: 'bosch-gsb-550-impact-drill', sku: 'PWR-001', brand: 'Bosch', categoryId: c[0], category: 'power-tools', price: 2499, compareAt: 3200, stock: 45, published: true, featured: true, displayOrder: 1, rating: 4.5, reviewCount: 128, description: '550W impact drill with keyless chuck. Ideal for drilling in wood, metal and masonry. Variable speed with reverse function.', images: ['https://images.unsplash.com/photo-1504148455328-c376907d081c?w=500'], tags: ['drill', 'bosch', 'impact'], createdAt: now, updatedAt: now },
    { title: 'Makita HP1631 Hammer Drill 710W', slug: 'makita-hp1631-hammer-drill', sku: 'PWR-002', brand: 'Makita', categoryId: c[0], category: 'power-tools', price: 3899, compareAt: 4500, stock: 30, published: true, featured: true, displayOrder: 2, rating: 4.7, reviewCount: 96, description: '710W hammer drill with 2-speed gear and variable speed control for precision drilling in concrete and masonry.', images: ['https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=500'], tags: ['drill', 'makita', 'hammer'], createdAt: now, updatedAt: now },
    { title: 'DeWalt DCS391 Circular Saw 165mm', slug: 'dewalt-dcs391-circular-saw', sku: 'PWR-003', brand: 'DeWalt', categoryId: c[0], category: 'power-tools', price: 8999, compareAt: 10500, stock: 20, published: true, featured: true, displayOrder: 3, rating: 4.8, reviewCount: 74, description: '18V cordless circular saw with 165mm blade. Up to 3700 RPM for fast, precise cuts in timber and sheet materials.', images: ['https://images.unsplash.com/photo-1617802690992-15d93263d3a9?w=500'], tags: ['saw', 'dewalt', 'cordless'], createdAt: now, updatedAt: now },
    { title: 'Bosch GWS 600 Angle Grinder 4"', slug: 'bosch-gws-600-angle-grinder', sku: 'PWR-004', brand: 'Bosch', categoryId: c[0], category: 'power-tools', price: 1799, compareAt: 2200, stock: 60, published: true, featured: false, displayOrder: 4, rating: 4.4, reviewCount: 203, description: '670W angle grinder with 4-inch disc. Compact design for grinding, cutting and polishing metal surfaces.', images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500'], tags: ['grinder', 'bosch', 'angle'], createdAt: now, updatedAt: now },
    { title: 'Milwaukee M18 Cordless Drill Driver', slug: 'milwaukee-m18-cordless-drill', sku: 'PWR-005', brand: 'Milwaukee', categoryId: c[0], category: 'power-tools', price: 7499, compareAt: 8999, stock: 18, published: true, featured: true, displayOrder: 5, rating: 4.9, reviewCount: 52, description: '18V brushless cordless drill driver with 13mm chuck and 2-speed gearbox. Includes 2 batteries and charger.', images: ['https://images.unsplash.com/photo-1504148455328-c376907d081c?w=500'], tags: ['drill', 'milwaukee', 'cordless'], createdAt: now, updatedAt: now },

    { title: 'Stanley 16oz Claw Hammer', slug: 'stanley-16oz-claw-hammer', sku: 'HND-001', brand: 'Stanley', categoryId: c[1], category: 'hand-tools', price: 499, compareAt: 650, stock: 150, published: true, featured: false, displayOrder: 1, rating: 4.3, reviewCount: 312, description: 'Professional 16oz steel claw hammer with anti-vibration grip handle. Forged steel head with polished face.', images: ['https://images.unsplash.com/photo-1586864387967-d02ef85d93e8?w=500'], tags: ['hammer', 'stanley', 'claw'], createdAt: now, updatedAt: now },
    { title: 'Taparia Combination Plier 8"', slug: 'taparia-combination-plier-8inch', sku: 'HND-002', brand: 'Taparia', categoryId: c[1], category: 'hand-tools', price: 349, compareAt: 450, stock: 200, published: true, featured: false, displayOrder: 2, rating: 4.2, reviewCount: 445, description: 'Drop forged alloy steel 8-inch combination plier with induction hardened teeth and PVC insulated handles.', images: ['https://images.unsplash.com/photo-1530124566582-a618bc2615dc?w=500'], tags: ['plier', 'taparia'], createdAt: now, updatedAt: now },
    { title: 'Gedore 19-Piece Socket Wrench Set', slug: 'gedore-socket-wrench-set', sku: 'HND-003', brand: 'Gedore', categoryId: c[1], category: 'hand-tools', price: 2299, compareAt: 2800, stock: 35, published: true, featured: true, displayOrder: 3, rating: 4.6, reviewCount: 89, description: '19-piece 1/2 inch drive socket set in blow mould case. Chrome vanadium steel sockets from 10-32mm.', images: ['https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=500'], tags: ['socket', 'wrench', 'gedore', 'set'], createdAt: now, updatedAt: now },
    { title: 'Craftsman Screwdriver Set 10pc', slug: 'craftsman-screwdriver-set-10pc', sku: 'HND-004', brand: 'Craftsman', categoryId: c[1], category: 'hand-tools', price: 799, compareAt: 999, stock: 80, published: true, featured: false, displayOrder: 4, rating: 4.4, reviewCount: 167, description: '10-piece screwdriver set with Phillips and flat head variants. Tri-material comfort grip handles.', images: ['https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=500'], tags: ['screwdriver', 'craftsman', 'set'], createdAt: now, updatedAt: now },

    { title: 'Carbon Brush Set for Bosch GBH Drills', slug: 'carbon-brush-bosch-gbh', sku: 'SPA-001', brand: 'Bosch', categoryId: c[2], category: 'spare-parts', price: 189, compareAt: 250, stock: 500, published: true, featured: false, displayOrder: 1, rating: 4.1, reviewCount: 78, description: 'Genuine carbon brush set compatible with Bosch GBH series rotary hammers. Pack of 2 brushes.', images: ['https://images.unsplash.com/photo-1609205698526-b22de6ab8534?w=500'], tags: ['carbon', 'brush', 'bosch', 'spare'], createdAt: now, updatedAt: now },
    { title: 'Angle Grinder Gear Set Universal', slug: 'angle-grinder-gear-set', sku: 'SPA-002', brand: 'Generic', categoryId: c[2], category: 'spare-parts', price: 449, compareAt: 599, stock: 120, published: true, featured: false, displayOrder: 2, rating: 3.9, reviewCount: 34, description: 'Universal bevel gear set for 4-inch angle grinders. Compatible with Bosch, Makita and similar brands.', images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500'], tags: ['gear', 'grinder', 'spare'], createdAt: now, updatedAt: now },
    { title: 'Makita 13mm Drill Chuck Replacement', slug: 'makita-drill-chuck-13mm', sku: 'SPA-003', brand: 'Makita', categoryId: c[2], category: 'spare-parts', price: 699, compareAt: 899, stock: 75, published: true, featured: false, displayOrder: 3, rating: 4.3, reviewCount: 56, description: 'Genuine Makita 13mm keyless drill chuck replacement for HP and DP series drill machines.', images: ['https://images.unsplash.com/photo-1504148455328-c376907d081c?w=500'], tags: ['chuck', 'makita', 'spare'], createdAt: now, updatedAt: now },
    { title: 'Circular Saw Blade 7.25" 24T Wood', slug: 'circular-saw-blade-7inch-24t', sku: 'SPA-004', brand: 'DeWalt', categoryId: c[2], category: 'spare-parts', price: 599, compareAt: 750, stock: 200, published: true, featured: false, displayOrder: 4, rating: 4.5, reviewCount: 143, description: '7.25 inch 24-tooth carbide tipped circular saw blade for fast ripping in softwood and hardwood.', images: ['https://images.unsplash.com/photo-1617802690992-15d93263d3a9?w=500'], tags: ['blade', 'saw', 'dewalt'], createdAt: now, updatedAt: now },

    { title: 'Lathe Machine 6x18 Bench Top 750W', slug: 'lathe-machine-6x18-bench', sku: 'MAC-001', brand: 'HiTech', categoryId: c[3], category: 'machines', price: 45999, compareAt: 52000, stock: 5, published: true, featured: true, displayOrder: 1, rating: 4.6, reviewCount: 23, description: '6x18 inch bench top metal lathe with 750W motor. Variable speed 100-2500 RPM. Ideal for small workshops.', images: ['https://images.unsplash.com/photo-1565945887714-d5139f4eb0ce?w=500'], tags: ['lathe', 'machine', 'bench'], createdAt: now, updatedAt: now },
    { title: 'Drill Press 16-Speed 550W Bench', slug: 'drill-press-bench-16speed', sku: 'MAC-002', brand: 'JET', categoryId: c[3], category: 'machines', price: 18999, compareAt: 22000, stock: 8, published: true, featured: true, displayOrder: 2, rating: 4.5, reviewCount: 41, description: '16-speed bench drill press with 550W motor and 16mm chuck capacity. Adjustable table with rack and pinion.', images: ['https://images.unsplash.com/photo-1504148455328-c376907d081c?w=500'], tags: ['drill', 'press', 'bench'], createdAt: now, updatedAt: now },
    { title: 'Band Saw Machine 14" 1HP', slug: 'band-saw-machine-14inch', sku: 'MAC-003', brand: 'WEN', categoryId: c[3], category: 'machines', price: 32999, compareAt: 38000, stock: 4, published: true, featured: false, displayOrder: 3, rating: 4.4, reviewCount: 18, description: '14-inch 1HP band saw with 6-inch resaw capacity, fence system and adjustable blade guide.', images: ['https://images.unsplash.com/photo-1617802690992-15d93263d3a9?w=500'], tags: ['bandsaw', 'machine', 'woodworking'], createdAt: now, updatedAt: now },

    { title: 'MSA V-Gard Safety Helmet White', slug: 'msa-vgard-safety-helmet-white', sku: 'SAF-001', brand: 'MSA', categoryId: c[4], category: 'safety', price: 649, compareAt: 850, stock: 300, published: true, featured: false, displayOrder: 1, rating: 4.7, reviewCount: 534, description: 'MSA V-Gard polycarbonate safety helmet. Meets IS 2925 standard. Adjustable ratchet suspension system.', images: ['https://images.unsplash.com/photo-1601597111158-2fceff292cdc?w=500'], tags: ['helmet', 'safety', 'msa', 'hardhat'], createdAt: now, updatedAt: now },
    { title: '3M 6200 Half Face Respirator Medium', slug: '3m-6200-half-face-respirator', sku: 'SAF-002', brand: '3M', categoryId: c[4], category: 'safety', price: 1299, compareAt: 1599, stock: 150, published: true, featured: false, displayOrder: 2, rating: 4.8, reviewCount: 289, description: '3M 6200 half-face respirator for protection against dust, fumes and mists. Compatible with 6000 series filters.', images: ['https://images.unsplash.com/photo-1584036561566-baf8f5f1b144?w=500'], tags: ['respirator', '3m', 'safety', 'mask'], createdAt: now, updatedAt: now },
    { title: 'Honeywell Anti-Fog Safety Goggles', slug: 'honeywell-safety-goggles-antifog', sku: 'SAF-003', brand: 'Honeywell', categoryId: c[4], category: 'safety', price: 399, compareAt: 550, stock: 400, published: true, featured: false, displayOrder: 3, rating: 4.3, reviewCount: 178, description: 'Anti-fog polycarbonate safety goggles with adjustable elastic strap. UV400 protection for industrial use.', images: ['https://images.unsplash.com/photo-1609205698526-b22de6ab8534?w=500'], tags: ['goggles', 'safety', 'honeywell'], createdAt: now, updatedAt: now },

    { title: 'Mitutoyo Vernier Caliper 6" 0.02mm', slug: 'mitutoyo-vernier-caliper-6inch', sku: 'MEA-001', brand: 'Mitutoyo', categoryId: c[5], category: 'measuring-tools', price: 1899, compareAt: 2200, stock: 60, published: true, featured: true, displayOrder: 1, rating: 4.9, reviewCount: 312, description: 'Mitutoyo 6-inch vernier caliper with 0.02mm resolution. Hardened stainless steel jaws for durability.', images: ['https://images.unsplash.com/photo-1609205698526-b22de6ab8534?w=500'], tags: ['caliper', 'mitutoyo', 'measuring'], createdAt: now, updatedAt: now },
    { title: 'Bosch GLM 50 Laser Distance Meter', slug: 'bosch-glm50-laser-distance-meter', sku: 'MEA-002', brand: 'Bosch', categoryId: c[5], category: 'measuring-tools', price: 3499, compareAt: 4200, stock: 40, published: true, featured: false, displayOrder: 2, rating: 4.7, reviewCount: 156, description: 'Bosch GLM 50 laser distance meter with 50m range and plus or minus 1.5mm accuracy. Backlit display.', images: ['https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=500'], tags: ['laser', 'distance', 'bosch', 'measuring'], createdAt: now, updatedAt: now },
    { title: 'Stanley FatMax Tape Measure 5m', slug: 'stanley-fatmax-tape-measure-5m', sku: 'MEA-003', brand: 'Stanley', categoryId: c[5], category: 'measuring-tools', price: 549, compareAt: 699, stock: 250, published: true, featured: false, displayOrder: 3, rating: 4.5, reviewCount: 423, description: 'Stanley FatMax 5m tape measure with magnetic tip and Tru-Zero hook. Blade standout of 3m.', images: ['https://images.unsplash.com/photo-1530124566582-a618bc2615dc?w=500'], tags: ['tape', 'measure', 'stanley'], createdAt: now, updatedAt: now },

    { title: 'Lincoln Electric Stick Welder 225A', slug: 'lincoln-stick-welder-225a', sku: 'WLD-001', brand: 'Lincoln Electric', categoryId: c[6], category: 'welding', price: 12999, compareAt: 15000, stock: 12, published: true, featured: true, displayOrder: 1, rating: 4.8, reviewCount: 67, description: '225A AC stick welder for farm, home and light fabrication. Runs on 230V single phase. Includes electrode holder and clamp.', images: ['https://images.unsplash.com/photo-1565945887714-d5139f4eb0ce?w=500'], tags: ['welder', 'lincoln', 'stick', 'welding'], createdAt: now, updatedAt: now },
    { title: 'Esab Auto-Darkening Welding Helmet', slug: 'esab-auto-darkening-welding-helmet', sku: 'WLD-002', brand: 'Esab', categoryId: c[6], category: 'welding', price: 2799, compareAt: 3500, stock: 55, published: true, featured: false, displayOrder: 2, rating: 4.5, reviewCount: 134, description: 'Solar powered auto-darkening welding helmet. Shade 9-13 DIN. Lightweight ABS shell with large viewing area.', images: ['https://images.unsplash.com/photo-1601597111158-2fceff292cdc?w=500'], tags: ['helmet', 'welding', 'auto', 'esab'], createdAt: now, updatedAt: now },

    { title: 'Freud 10" 80T Fine Finish Saw Blade', slug: 'freud-10inch-80t-saw-blade', sku: 'CUT-001', brand: 'Freud', categoryId: c[7], category: 'cutting-tools', price: 1599, compareAt: 1999, stock: 80, published: true, featured: false, displayOrder: 1, rating: 4.8, reviewCount: 94, description: 'Freud 10-inch 80-tooth TCG grind saw blade for ultra-fine crosscuts in hardwood and plywood.', images: ['https://images.unsplash.com/photo-1617802690992-15d93263d3a9?w=500'], tags: ['blade', 'freud', 'cutting', 'fine'], createdAt: now, updatedAt: now },
    { title: 'Bosch 115mm Metal Cutting Disc Pack 25', slug: 'bosch-115mm-cutting-disc-25pk', sku: 'CUT-002', brand: 'Bosch', categoryId: c[7], category: 'cutting-tools', price: 899, compareAt: 1200, stock: 300, published: true, featured: false, displayOrder: 2, rating: 4.3, reviewCount: 267, description: 'Pack of 25 Bosch 115mm cutting discs for cutting metal and stainless steel. For use with 4-inch angle grinders.', images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500'], tags: ['disc', 'cutting', 'bosch', 'metal'], createdAt: now, updatedAt: now },
  ];

  await db.collection('products').insertMany(products);
  console.log('Products inserted:', products.length);

  // Upsert admin user
  const adminEmail = 'admin@macgly.com';
  const adminPassword = await bcrypt.hash('Admin@1234', 12);
  await db.collection('users').updateOne(
    { email: adminEmail },
    { $set: { name: 'Admin', email: adminEmail, password: adminPassword, role: 'admin', isActive: true, emailVerified: true, createdAt: now, updatedAt: now } },
    { upsert: true }
  );
  console.log('Admin user: admin@macgly.com / Admin@1234');

  process.exit(0);
}).catch(e => { console.error(e.message); process.exit(1); });
